### ISSUE TITLE
doesn't work with my local project

### ISSUE THREAD

**Issue by jerome-laforge** [cugu/gocap#3]
in my local project (that means directory with go.mod & go.sum), when I run 
```sh
cd myWonderfullProject

ls 
go.mod  go.sum main.go

gocap generate .
could not parse package path
```

I expect that go.cap has been generated with all modules (direct & transitive) pined into my go.mod & go.sum.

**Comment by cugu** [comment]
Can you provide some more information? The content of the `main.go` and the output of `go list --json .` should help.

**Comment by jerome-laforge** [comment]
I think the root cause is the directory, that contains go.mod & go.sum, doesn't contain go files, that is not acctually in my previous given example.

so I give another example:
```sh
mkdir -p /tmp/myWonderfullProject/cmd/myWonderfullProject
cd /tmp/myWonderfullProject

echo 'package main

import "github.com/gin-gonic/gin"

func main() {
        r := gin.Default()
        r.GET("/ping", func(c *gin.Context) {
                c.JSON(200, gin.H{
                        "message": "pong",
                })
        })
        r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}' > /tmp/myWonderfullProject/cmd/myWonderfullProject/main.go


go mod tidy
tree /tmp/myWonderfullProject
/tmp/myWonderfullProject
├── cmd
│   └── myWonderfullProject
│       └── main.go
├── go.mod
└── go.sum

gocap generate /tmp/myWonderfullProject
could not parse package path
```

**Comment by Dentrax** [comment]
+1, If I run the following, there is an error in the `go.cap` file: `could not parse package path`:

```
$ gocap generate github.com/sigstore/cosign > go.cap
$ cat go.cap
could not parse package path
```

**Comment by cugu** [comment]
In these cases /tmp/myWonderfullProject and github.com/sigstore/cosign are not Go packages (they do not contain any go files). `gocap generate` works on package basis. I should elaborate that more in the readme.

`cd /tmp/myWonderfullProject && gocap generate ./cmd/myWonderfullProject > go.cap` should work.
as well as
`gocap generate ./cmd/cosign > go.cap` (although this melts my CPU and takes 5min on my laptop because of the high number of dependencies).

Then you can check with `cd /tmp/myWonderfullProject && gocap check ./cmd/myWonderfullProject` or `gocap check ./cmd/cosign`

**Comment by jerome-laforge** [comment]
> `cd /tmp/myWonderfullProject && gocap generate ./cmd/myWonderfullProject > go.cap` should work.
as well as

Thx for this workaround, it works fine.
Maybe you can just close this issue, after you will update the readme?

**Comment by Dentrax** [comment]
@cugu thanks for clarification. But the following `check` command does not read `go.cap` file i think. 🤔 

```
$ gocap generate ./cmd/myWonderfullProject > go.cap
$ gocap check go.cap
could not parse package path
```

**Comment by cugu** [comment]
Try `gocap check ./cmd/myWonderfullProject`
