### ISSUE TITLE
ux: go check should generate .cap if does not exist

### ISSUE THREAD

**Issue by Dentrax** [cugu/gocap#4]
Thanks for the such a cool project! Just have been trying this out!

----

I think it had better to call `generate` command under the hood if `go.cap` file does not exit. Or we can rephrase this warning to: `go.cap file does not exist, consider run generate command` for example. 

```
$ gocap check .
go.cap file does not exist
```

What do you think?

**Comment by cugu** [comment]
Should be solved in #5
